[project]
name = "threedx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tim Radtke", email = "tim@timradtke.net" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24,<3",
]

[project.scripts]
threedx = "threedx:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
