[project]
name = "threedx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tim Radtke", email = "tim@timradtke.net" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24,<3",
]

[project.scripts]
threedx = "threedx:main"

[project.optional-dependencies]
graphics = [
    "matplotlib>=3.11.1",
]
docs = [
    "fev>=0.10.0",
    "furo>=2025.12.19",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "nbsphinx>=0.9.8",
    "sphinx>=9.1.0",
    "sphinx-mdinclude>=0.6.2",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
]
